const fs=require('node:fs'),assert=require('node:assert/strict');
const path=require('node:path');
const dependency=name=>require(process.env.NCD_TEST_NODE_MODULES?path.join(process.env.NCD_TEST_NODE_MODULES,name):name);
const {PGlite}=dependency('@electric-sql/pglite');
const {parseHTML}=dependency('linkedom');
(async()=>{
 const html=fs.readFileSync('index.html','utf8'),app=fs.readFileSync('app.js','utf8');
 const {document}=parseHTML(html),pulse=document.querySelector('#ncd-pulse');
 assert(pulse&&pulse.name==='pulse'&&!pulse.hasAttribute('required'));
 assert(document.querySelector('#ncd-dbp').closest('.measure-card').nextElementSibling.contains(pulse));
 assert(app.includes("supabase.rpc('save_health_ncd_screening_v6'"));
 const migration=fs.readFileSync('supabase/migrations/20261004080138_ncd_pulse_cloud_local.sql','utf8');
 const sig=migration.match(/save_health_ncd_screening_v6\((.*?)\)\nRETURNS/s)[1];
 const oldsig=sig.replace(/, p_pulse integer DEFAULT NULL$/,'');
 const db=new PGlite();
 await db.exec(`CREATE SCHEMA auth; CREATE SCHEMA private; CREATE ROLE anon; CREATE ROLE authenticated; CREATE ROLE service_role;
 CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql AS $$SELECT nullif(current_setting('test.uid',true),'')::uuid$$;
 CREATE FUNCTION private.current_role() RETURNS text LANGUAGE sql AS $$SELECT 'osm'::text$$;
 CREATE TABLE public.health_ncd_screenings(id uuid DEFAULT gen_random_uuid() PRIMARY KEY, recorded_by uuid,request_id uuid,sbp integer,dbp integer,sbp_repeat integer,dbp_repeat integer);
 CREATE TABLE public.health_audit_log(operator_id uuid,entity text,entity_id text,details jsonb);
 CREATE FUNCTION public.save_health_ncd_screening_v5(${oldsig}) RETURNS public.health_ncd_screenings LANGUAGE plpgsql AS $$DECLARE r public.health_ncd_screenings; BEGIN INSERT INTO public.health_ncd_screenings(recorded_by,request_id,sbp,dbp,sbp_repeat,dbp_repeat) VALUES(auth.uid(),p_request_id,p_sbp,p_dbp,p_sbp_repeat,p_dbp_repeat) RETURNING * INTO r; RETURN r; END;$$;`);
 await db.exec(migration.split('CREATE OR REPLACE VIEW')[0]);
 const call=(id,p)=>`SELECT (public.save_health_ncd_screening_v6('99999',1,current_date,60,165,80,120,80,100,'unknown',false,'never','never','daily','', '${id}',null,null,140,90,${p})).*`;
 const id='00000000-0000-0000-0000-000000000001';
 await assert.rejects(db.query(call(id,72)),/Not authorized/);
 await db.exec("SET test.uid='00000000-0000-0000-0000-000000000002'");
 let r=(await db.query(call(id,72))).rows[0];assert.equal(r.pulse,72);assert.equal(r.sbp_repeat,140);
 r=(await db.query(call(id,99))).rows[0];assert.equal(r.pulse,72);
 const next='00000000-0000-0000-0000-000000000003';
 await assert.rejects(db.query(call(next,19)),/invalid pulse/);
 await assert.rejects(db.query(call(next,251)),/invalid pulse/);
 r=(await db.query(call(next,'NULL'))).rows[0];assert.equal(r.pulse,null);
 await assert.rejects(db.exec('UPDATE public.health_ncd_screenings SET pulse=0'),/check constraint/);
 await db.close();console.log('Cloud form order, optional field, SQL auth, bounds, BP preservation, NULL and replay passed');
})().catch(e=>{console.error(e);process.exitCode=1});
