const fs=require('fs'),vm=require('vm'),assert=require('assert/strict');
const s=fs.readFileSync('app.js','utf8');const guard=s.slice(s.indexOf('function ncdEntryGuardV2122('),s.indexOf('function ensureBpRepeatUiV2123('));
let confirmed=0,answer=false;
const context=vm.createContext({bpRepeatStateV2123:form=>({effectiveSbp:Number(form.elements.sbp.value),effectiveDbp:Number(form.elements.dbp.value),anyGrade3:false}),confirm:()=>{confirmed++;return answer;}});vm.runInContext(guard,context);
const form=(overrides={})=>{const v={weight_kg:60,height_cm:165,waist_cm:80,sbp:120,dbp:80,glucose_mg_dl:90,pulse:72,...overrides};return {elements:Object.fromEntries(Object.entries(v).map(([k,x])=>[k,{value:String(x)}])),querySelector:()=>({value:'fasting'})};};
const check=(f,p={})=>context.ncdEntryGuardV2122(f,p);
assert.equal(check(form()).verify.length,0);assert.equal(check(form()).clinical.length,0);
assert(check(form({height_cm:220,weight_kg:53}),{previous_height_cm:220}).verify.some(x=>x.includes('ส่วนสูง')));
assert(check(form({height_cm:172}),{previous_height_cm:165}).verify.some(x=>x.includes('ครั้งก่อน')));
assert(check(form({weight_kg:72}),{previous_weight_kg:60}).verify.some(x=>x.includes('ครั้งก่อน')));
assert(check(form({waist_cm:95}),{previous_waist_cm:80}).verify.some(x=>x.includes('รอบเอว')));
assert(check(form({sbp:135}),{previous_sbp:100}).verify.some(x=>x.includes('ความดันตัวบน')));
assert(check(form({dbp:85}),{previous_dbp:60}).verify.some(x=>x.includes('ความดันตัวล่าง')));
assert(check(form({pulse:130})).verify.some(x=>x.includes('ชีพจร')));
assert(!check(form({pulse:''})).verify.some(x=>x.includes('ชีพจร')));
assert(!check(form(),{previous_height_cm:null,previous_weight_kg:null}).verify.some(x=>x.includes('ครั้งก่อน')));
assert(check(form({glucose_mg_dl:110})).clinical.length);
assert.equal(context.confirmNcdEntryGuardV2122(form({height_cm:220}),{}),false);
answer=true;assert.equal(context.confirmNcdEntryGuardV2122(form({height_cm:220}),{}),true);assert.equal(confirmed,2);
console.log('12 Cloud guard scenarios passed: normal, 220 unchanged, history deltas, optional pulse, glucose and cancel/confirm');
