alter table public.houses
  add column if not exists house_id_11 text,
  add column if not exists entry_source text not null default 'import',
  add column if not exists created_by_user_id uuid,
  add column if not exists created_by_volunteer_pid bigint,
  add column if not exists field_created_at timestamptz;

alter table public.houses drop constraint if exists houses_house_id_11_check;
alter table public.houses add constraint houses_house_id_11_check
  check (house_id_11 is null or house_id_11 ~ '^[0-9]{11}$');

alter table public.houses drop constraint if exists houses_entry_source_check;
alter table public.houses add constraint houses_entry_source_check
  check (entry_source in ('import','field'));

create unique index if not exists houses_house_id_11_unique
  on public.houses(house_id_11)
  where house_id_11 is not null;

create index if not exists houses_field_creator_idx
  on public.houses(created_by_volunteer_pid)
  where entry_source='field';

create table if not exists public.house_registration_audit (
  id bigint generated by default as identity primary key,
  house_id uuid not null,
  user_id uuid not null,
  role text not null,
  volunteer_pid bigint,
  action text not null check (action in ('add','update')),
  before_data jsonb,
  after_data jsonb,
  created_at timestamptz not null default now()
);
alter table public.house_registration_audit enable row level security;
revoke all on public.house_registration_audit from anon, authenticated;
grant all on public.house_registration_audit to service_role;

revoke all on public.houses from anon;
revoke insert, update, delete, truncate, references, trigger on public.houses from authenticated;
grant select on public.houses to authenticated;

create or replace function public.house_add_quota()
returns jsonb
language plpgsql
security definer
set search_path = public, private, extensions
as $$
declare
  v_uid uuid := auth.uid();
  v_profile public.profiles%rowtype;
  v_used integer := 0;
begin
  if v_uid is null then raise exception 'AUTH_REQUIRED'; end if;
  select * into v_profile from public.profiles where user_id=v_uid and active=true;
  if not found then raise exception 'PROFILE_NOT_ACTIVE'; end if;

  if v_profile.role='admin' then
    return jsonb_build_object('limit',null,'used',0,'remaining',null,'role',v_profile.role);
  end if;
  if v_profile.role not in ('staff','user') or v_profile.volunteer_pid is null then
    raise exception 'HOUSE_ADD_NOT_ALLOWED';
  end if;

  select count(*) into v_used
  from public.houses
  where entry_source='field'
    and created_by_volunteer_pid=v_profile.volunteer_pid;

  return jsonb_build_object(
    'limit',30,
    'used',v_used,
    'remaining',greatest(30-v_used,0),
    'role',v_profile.role
  );
end;
$$;

create or replace function public.add_house_field(
  p_house_no text,
  p_house_id_11 text,
  p_latitude double precision,
  p_longitude double precision,
  p_source text default 'gps',
  p_community text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public, private, extensions
as $$
declare
  v_uid uuid := auth.uid();
  v_profile public.profiles%rowtype;
  v_community public.communities%rowtype;
  v_house public.houses%rowtype;
  v_point extensions.geometry;
  v_house_no text := btrim(coalesce(p_house_no,''));
  v_house_no_key text;
  v_house_id text := btrim(coalesce(p_house_id_11,''));
  v_source text := lower(btrim(coalesce(p_source,'gps')));
  v_community_name text;
  v_count integer := 0;
  v_inside_tambon boolean := false;
  v_inside_community boolean := false;
  v_new_id uuid := extensions.gen_random_uuid();
  v_hcode text;
begin
  if v_uid is null then raise exception 'AUTH_REQUIRED'; end if;
  select * into v_profile from public.profiles where user_id=v_uid and active=true;
  if not found then raise exception 'PROFILE_NOT_ACTIVE'; end if;
  if v_profile.role not in ('admin','staff','user') then raise exception 'HOUSE_ADD_NOT_ALLOWED'; end if;

  if v_house_no='' or length(v_house_no)>50 then raise exception 'INVALID_HOUSE_NO'; end if;
  v_house_no_key := lower(regexp_replace(v_house_no,'\s+','','g'));
  if v_house_id !~ '^[0-9]{11}$' then raise exception 'HOUSE_ID_11_REQUIRED'; end if;
  if p_latitude is null or p_longitude is null or p_latitude < 5 or p_latitude > 21 or p_longitude < 97 or p_longitude > 106 then
    raise exception 'INVALID_COORDINATES';
  end if;
  if v_source not in ('gps','map') then raise exception 'INVALID_COORDINATE_SOURCE'; end if;

  v_community_name := case
    when v_profile.role='admin' then btrim(coalesce(p_community,''))
    else btrim(coalesce(v_profile.community,''))
  end;
  if v_community_name='' then raise exception 'COMMUNITY_REQUIRED'; end if;

  select * into v_community
  from public.communities
  where active=true and btrim(name)=v_community_name
  limit 1;
  if not found then raise exception 'COMMUNITY_NOT_FOUND'; end if;

  if v_profile.role='staff' and btrim(v_community.name)<>btrim(v_profile.community) then
    raise exception 'HOUSE_OUT_OF_SCOPE';
  end if;

  v_point := extensions.st_setsrid(extensions.st_makepoint(p_longitude,p_latitude),4326);

  select exists(
    select 1 from public.tambon_boundaries t
    where t.tambon_code='520105'
      and t.geom is not null
      and extensions.st_covers(extensions.st_makevalid(t.geom),v_point)
  ) into v_inside_tambon;
  if not v_inside_tambon then raise exception 'OUTSIDE_TAMBON'; end if;

  select coalesce(extensions.st_covers(extensions.st_makevalid(v_community.geom),v_point),false)
    into v_inside_community;
  if not v_inside_community then raise exception 'OUTSIDE_COMMUNITY'; end if;

  perform pg_advisory_xact_lock(pg_catalog.hashtextextended('house11:'||v_house_id,0));
  if exists(select 1 from public.houses where house_id_11=v_house_id) then
    raise exception 'DUPLICATE_HOUSE_ID_11';
  end if;

  perform pg_advisory_xact_lock(pg_catalog.hashtextextended('houseno:'||v_community.moo||':'||v_house_no_key,0));
  if exists(
    select 1 from public.houses h
    where btrim(h.moo)=btrim(v_community.moo)
      and lower(regexp_replace(btrim(h.house_no),'\s+','','g'))=v_house_no_key
  ) then
    raise exception 'DUPLICATE_HOUSE_NO_MOO';
  end if;

  if v_profile.role in ('staff','user') then
    if v_profile.volunteer_pid is null then raise exception 'VOLUNTEER_NOT_LINKED'; end if;
    perform pg_advisory_xact_lock(pg_catalog.hashtextextended('vhvquota:'||v_profile.volunteer_pid::text,0));
    select count(*) into v_count
    from public.houses
    where entry_source='field'
      and created_by_volunteer_pid=v_profile.volunteer_pid;
    if v_count >= 30 then raise exception 'VHV_HOUSE_LIMIT'; end if;
  end if;

  v_hcode := 'field-'||replace(v_new_id::text,'-','');

  insert into public.houses(
    id,source_pcucode,hcode,house_no,moo,community,
    latitude,longitude,geom,coordinate_source,coordinate_status,
    coordinate_distance_m,inside_tambon,inside_community,
    volunteer_pid,record_status,review_required,review_reason,
    house_id_11,entry_source,created_by_user_id,created_by_volunteer_pid,field_created_at,updated_at
  ) values (
    v_new_id,'06116',v_hcode,v_house_no,v_community.moo,v_community.name,
    p_latitude,p_longitude,v_point,v_source,
    case when v_profile.role='admin' then 'resolved_by_tambon' else 'resolved_by_community' end,
    null,true,true,
    case when v_profile.role='admin' then null else v_profile.volunteer_pid end,
    'เธขเธฑเธเนเธกเนเธขเธทเธเธขเธฑเธ',false,'',
    v_house_id,'field',v_uid,v_profile.volunteer_pid,now(),now()
  ) returning * into v_house;

  insert into public.house_registration_audit(house_id,user_id,role,volunteer_pid,action,before_data,after_data)
  values(v_house.id,v_uid,v_profile.role,v_profile.volunteer_pid,'add',null,to_jsonb(v_house));

  if v_profile.role in ('staff','user') then v_count := v_count + 1; end if;

  return jsonb_build_object(
    'success',true,
    'house_id',v_house.id,
    'house_no',v_house.house_no,
    'house_id_11',v_house.house_id_11,
    'moo',v_house.moo,
    'community',v_house.community,
    'latitude',v_house.latitude,
    'longitude',v_house.longitude,
    'inside_tambon',true,
    'inside_community',true,
    'quota_limit',case when v_profile.role='admin' then null else 30 end,
    'quota_used',case when v_profile.role='admin' then null else v_count end,
    'quota_remaining',case when v_profile.role='admin' then null else greatest(30-v_count,0) end
  );
end;
$$;

create or replace function public.update_house_field_details(
  p_house_id uuid,
  p_house_no text,
  p_house_id_11 text default null
)
returns jsonb
language plpgsql
security definer
set search_path = public, private, extensions
as $$
declare
  v_uid uuid := auth.uid();
  v_profile public.profiles%rowtype;
  v_house public.houses%rowtype;
  v_before public.houses%rowtype;
  v_house_no text := btrim(coalesce(p_house_no,''));
  v_house_no_key text;
  v_house_id text := nullif(btrim(coalesce(p_house_id_11,'')),'');
  v_allowed boolean := false;
begin
  if v_uid is null then raise exception 'AUTH_REQUIRED'; end if;
  select * into v_profile from public.profiles where user_id=v_uid and active=true;
  if not found then raise exception 'PROFILE_NOT_ACTIVE'; end if;

  select * into v_house from public.houses where id=p_house_id for update;
  if not found then raise exception 'HOUSE_NOT_FOUND'; end if;
  v_before := v_house;

  v_allowed := coalesce(
    v_profile.role='admin'
    or (v_profile.role='staff' and coalesce(btrim(v_profile.community),'')<>'' and btrim(v_house.community)=btrim(v_profile.community))
    or (v_profile.role='user' and v_profile.volunteer_pid is not null and v_house.volunteer_pid is not null and v_house.volunteer_pid=v_profile.volunteer_pid),
    false
  );
  if not v_allowed then raise exception 'HOUSE_OUT_OF_SCOPE'; end if;

  if v_house_no='' or length(v_house_no)>50 then raise exception 'INVALID_HOUSE_NO'; end if;
  v_house_no_key := lower(regexp_replace(v_house_no,'\s+','','g'));

  if v_house.entry_source='field' and v_house_id is null then raise exception 'HOUSE_ID_11_REQUIRED'; end if;
  if v_house_id is not null and v_house_id !~ '^[0-9]{11}$' then raise exception 'HOUSE_ID_11_REQUIRED'; end if;

  if v_house_id is not null then
    perform pg_advisory_xact_lock(pg_catalog.hashtextextended('house11:'||v_house_id,0));
    if exists(select 1 from public.houses where house_id_11=v_house_id and id<>v_house.id) then
      raise exception 'DUPLICATE_HOUSE_ID_11';
    end if;
  end if;

  perform pg_advisory_xact_lock(pg_catalog.hashtextextended('houseno:'||v_house.moo||':'||v_house_no_key,0));
  if exists(
    select 1 from public.houses h
    where h.id<>v_house.id
      and btrim(h.moo)=btrim(v_house.moo)
      and lower(regexp_replace(btrim(h.house_no),'\s+','','g'))=v_house_no_key
  ) then
    raise exception 'DUPLICATE_HOUSE_NO_MOO';
  end if;

  update public.houses
     set house_no=v_house_no,
         house_id_11=v_house_id,
         updated_at=now()
   where id=v_house.id
   returning * into v_house;

  insert into public.house_registration_audit(house_id,user_id,role,volunteer_pid,action,before_data,after_data)
  values(v_house.id,v_uid,v_profile.role,v_profile.volunteer_pid,'update',to_jsonb(v_before),to_jsonb(v_house));

  return jsonb_build_object('success',true,'house_id',v_house.id,'house_no',v_house.house_no,'house_id_11',v_house.house_id_11,'moo',v_house.moo,'community',v_house.community);
end;
$$;

create or replace function public.update_house_coordinates(
  p_house_id uuid,
  p_latitude double precision,
  p_longitude double precision,
  p_source text default 'gps'
)
returns jsonb
language plpgsql
security definer
set search_path = public, private, extensions
as $$
declare
  v_uid uuid := auth.uid();
  v_profile public.profiles%rowtype;
  v_house public.houses%rowtype;
  v_source text := lower(coalesce(p_source,'gps'));
  v_status text;
  v_allowed boolean := false;
  v_point extensions.geometry;
  v_community_geom extensions.geometry;
  v_inside_tambon boolean := false;
  v_inside_community boolean := false;
begin
  if v_uid is null then raise exception 'AUTH_REQUIRED'; end if;
  if p_latitude is null or p_longitude is null or p_latitude < 5 or p_latitude > 21 or p_longitude < 97 or p_longitude > 106 then
    raise exception 'INVALID_COORDINATES';
  end if;
  if v_source not in ('gps','map') then raise exception 'INVALID_COORDINATE_SOURCE'; end if;

  select * into v_profile from public.profiles where user_id=v_uid and active=true;
  if not found then raise exception 'PROFILE_NOT_ACTIVE'; end if;

  select * into v_house from public.houses where id=p_house_id for update;
  if not found then raise exception 'HOUSE_NOT_FOUND'; end if;

  v_allowed := coalesce(
    v_profile.role='admin'
    or (v_profile.role='staff' and coalesce(btrim(v_profile.community),'')<>'' and coalesce(btrim(v_house.community),'')=btrim(v_profile.community))
    or (v_profile.role='user' and v_profile.volunteer_pid is not null and v_house.volunteer_pid is not null and v_house.volunteer_pid=v_profile.volunteer_pid),
    false
  );
  if not v_allowed then raise exception 'HOUSE_OUT_OF_SCOPE'; end if;

  v_point := extensions.st_setsrid(extensions.st_makepoint(p_longitude,p_latitude),4326);

  select exists(
    select 1 from public.tambon_boundaries t
    where t.tambon_code='520105' and t.geom is not null
      and extensions.st_covers(extensions.st_makevalid(t.geom),v_point)
  ) into v_inside_tambon;
  if not v_inside_tambon then raise exception 'OUTSIDE_TAMBON'; end if;

  select c.geom into v_community_geom
  from public.communities c
  where c.active=true and btrim(c.name)=btrim(v_house.community)
  limit 1;
  if v_community_geom is null then raise exception 'COMMUNITY_NOT_FOUND'; end if;
  v_inside_community := coalesce(extensions.st_covers(extensions.st_makevalid(v_community_geom),v_point),false);
  if not v_inside_community then raise exception 'OUTSIDE_COMMUNITY'; end if;

  v_status := case when v_profile.role='admin' then 'resolved_by_tambon' else 'resolved_by_community' end;

  insert into public.house_coordinate_audit(
    house_id,user_id,role,source,
    old_latitude,old_longitude,new_latitude,new_longitude,
    old_coordinate_source,old_coordinate_status,old_coordinate_distance_m,
    old_inside_tambon,old_inside_community,old_review_required,old_review_reason,old_updated_at,
    new_coordinate_source,new_coordinate_status,new_review_required,new_review_reason
  ) values (
    v_house.id,v_uid,v_profile.role,v_source,
    v_house.latitude,v_house.longitude,p_latitude,p_longitude,
    v_house.coordinate_source,v_house.coordinate_status,v_house.coordinate_distance_m,
    v_house.inside_tambon,v_house.inside_community,v_house.review_required,v_house.review_reason,v_house.updated_at,
    v_source,v_status,false,''
  );

  update public.houses
     set latitude=p_latitude,
         longitude=p_longitude,
         geom=v_point,
         coordinate_source=v_source,
         coordinate_status=v_status,
         coordinate_distance_m=null,
         inside_tambon=true,
         inside_community=true,
         review_required=false,
         review_reason='',
         updated_at=now()
   where id=v_house.id;

  return jsonb_build_object('success',true,'house_id',v_house.id,'latitude',p_latitude,'longitude',p_longitude,'coordinate_source',v_source,'coordinate_status',v_status,'inside_tambon',true,'inside_community',true,'review_required',false,'saved_at',now());
end;
$$;

revoke all on function public.house_add_quota() from public, anon;
revoke all on function public.add_house_field(text,text,double precision,double precision,text,text) from public, anon;
revoke all on function public.update_house_field_details(uuid,text,text) from public, anon;
revoke all on function public.update_house_coordinates(uuid,double precision,double precision,text) from public, anon;
grant execute on function public.house_add_quota() to authenticated;
grant execute on function public.add_house_field(text,text,double precision,double precision,text,text) to authenticated;
grant execute on function public.update_house_field_details(uuid,text,text) to authenticated;
grant execute on function public.update_house_coordinates(uuid,double precision,double precision,text) to authenticated;

insert into public.app_settings(key,value)
values('house_field_registration_policy',jsonb_build_object(
  'version','1.8.19',
  'vhv_max_new_houses',30,
  'house_id_11_required_for_new',true,
  'house_id_11_unique',true,
  'house_number_unique_within_moo_for_new',true,
  'must_be_inside_tambon_phrabat',true,
  'must_be_inside_assigned_community',true,
  'vhv_can_add',true,
  'vhv_can_edit',true,
  'vhv_can_delete',false,
  'spatial_check','postgis_st_covers_makevalid'
))
on conflict (key) do update set value=excluded.value;
