SET lock_timeout='5s';
CREATE INDEX IF NOT EXISTS free_fk_01_hcv_demo_review_audit_v2094 ON "private"."hcv_demo_review_audit_v2094" (booking_id);
CREATE INDEX IF NOT EXISTS free_fk_02_hcv_demo_review_audit_v2094 ON "private"."hcv_demo_review_audit_v2094" (event_id);
CREATE INDEX IF NOT EXISTS free_fk_03_line_link_tokens_v190 ON "private"."line_link_tokens_v190" (app_user_id);
CREATE INDEX IF NOT EXISTS free_fk_04_line_login_requests_v201 ON "private"."line_login_requests_v201" (app_user_id);
CREATE INDEX IF NOT EXISTS free_fk_05_line_oauth_requests_v2012 ON "private"."line_oauth_requests_v2012" (app_user_id);
CREATE INDEX IF NOT EXISTS free_fk_06_linehub_notification_ingress_v1 ON "private"."linehub_notification_ingress_v1" (notification_id);
CREATE INDEX IF NOT EXISTS free_fk_07_age_screening_campaigns_v206 ON "public"."age_screening_campaigns_v206" (updated_by);
CREATE INDEX IF NOT EXISTS free_fk_08_appointment_responses ON "public"."appointment_responses" (app_user_id);
CREATE INDEX IF NOT EXISTS free_fk_09_appointments ON "public"."appointments" (app_user_id);
CREATE INDEX IF NOT EXISTS free_fk_10_appointments ON "public"."appointments" (created_by);
CREATE INDEX IF NOT EXISTS free_fk_11_child_development_screenings ON "public"."child_development_screenings" (reference_target_months);
CREATE INDEX IF NOT EXISTS free_fk_12_child_development_screenings ON "public"."child_development_screenings" (screened_by);
CREATE INDEX IF NOT EXISTS free_fk_13_child_development_screenings ON "public"."child_development_screenings" (session_id);
CREATE INDEX IF NOT EXISTS free_fk_14_elderly9_domain_results ON "public"."elderly9_domain_results" (assessed_by);
CREATE INDEX IF NOT EXISTS free_fk_15_h7_preliminary_requests_v2108 ON "public"."h7_preliminary_requests_v2108" (requested_by);
CREATE INDEX IF NOT EXISTS free_fk_16_h7_preliminary_requests_v2108 ON "public"."h7_preliminary_requests_v2108" (slot_id);
CREATE INDEX IF NOT EXISTS free_fk_17_health_growth_screenings ON "public"."health_growth_screenings" (screened_by);
CREATE INDEX IF NOT EXISTS free_fk_18_health_growth_screenings ON "public"."health_growth_screenings" (session_id);
CREATE INDEX IF NOT EXISTS free_fk_19_health_screening_target_groups_v2026 ON "public"."health_screening_target_groups_v2026" (updated_by);
CREATE INDEX IF NOT EXISTS free_fk_20_house_reconcile_audit_v2048 ON "public"."house_reconcile_audit_v2048" (canonical_house_id);
CREATE INDEX IF NOT EXISTS free_fk_21_line_message_group_members ON "public"."line_message_group_members" (app_user_id);
CREATE INDEX IF NOT EXISTS free_fk_22_line_message_groups ON "public"."line_message_groups" (created_by);
CREATE INDEX IF NOT EXISTS free_fk_23_line_messages ON "public"."line_messages" (created_by);
CREATE INDEX IF NOT EXISTS free_fk_24_mental_health_2q_screenings_v206 ON "public"."mental_health_2q_screenings_v206" (screened_by);
CREATE INDEX IF NOT EXISTS free_fk_25_screening_followups ON "public"."screening_followups" (created_by);
CREATE INDEX IF NOT EXISTS free_fk_26_screening_followups ON "public"."screening_followups" (source_pcucode,source_pid);
CREATE INDEX IF NOT EXISTS free_fk_27_screening_followups ON "public"."screening_followups" (updated_by);
CREATE INDEX IF NOT EXISTS free_fk_28_screening_sessions ON "public"."screening_sessions" (house_pcucode,hcode);
CREATE INDEX IF NOT EXISTS free_fk_29_screening_sessions ON "public"."screening_sessions" (ncd_screening_id);
CREATE INDEX IF NOT EXISTS free_fk_30_screening_sessions ON "public"."screening_sessions" (started_by);
CREATE INDEX IF NOT EXISTS free_fk_31_screening_test_reset_archive_v208 ON "public"."screening_test_reset_archive_v208" (reset_by);
ALTER TABLE public.health_screening_target_cache_v2030 ADD CONSTRAINT health_screening_target_cache_v2030_pkey PRIMARY KEY USING INDEX health_screening_target_cache_pk_v2030;

