-- OSM PHC Cloud schema for Supabase
-- No Thai citizen 13-digit identifier is stored in this schema.
-- JHCIS person linkage uses source_pcucode + source_pid only.

create extension if not exists pgcrypto with schema extensions;

create extension if not exists postgis with schema extensions;

create schema if not exists private;

revoke all on schema private from public, anon, authenticated;

create table if not exists public.profiles (
  user_id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null default '',
  role text not null check (role in ('admin','coordinator','viewer','volunteer')),
  community text not null default '',
  volunteer_pid bigint,
  active boolean not null default false,
  updated_at timestamptz not null default now()
);

create table if not exists public.communities (
  id bigint generated by default as identity primary key,
  moo text not null default '',
  name text not null unique,
  active boolean not null default true,
  geometry_geojson jsonb,
  geom extensions.geometry(MultiPolygon,4326),
  source text not null default 'j-report',
  source_hash text not null default '',
  updated_at timestamptz not null default now()
);

create table if not exists public.tambon_boundaries (
  tambon_code text primary key,
  tambon_name_th text not null,
  amphoe_code text not null default '',
  province_code text not null default '',
  geometry_geojson jsonb not null,
  geom extensions.geometry(MultiPolygon,4326),
  source text not null default 'DPM_TH_Boundary',
  source_hash text not null default '',
  updated_at timestamptz not null default now()
);

create table if not exists public.volunteers (
  id uuid primary key default extensions.gen_random_uuid(),
  source_pcucode text not null default '',
  source_pid bigint not null,
  display_name text not null,
  community text not null default '',
  moo text not null default '',
  anchor_hcode text not null default '',
  anchor_latitude double precision,
  anchor_longitude double precision,
  anchor_status text not null default 'missing' check (anchor_status in ('confirmed','community_review','outside_tambon','missing')),
  active boolean not null default true,
  updated_at timestamptz not null default now(),
  unique(source_pcucode, source_pid)
);

create table if not exists public.houses (
  id uuid primary key default extensions.gen_random_uuid(),
  source_pcucode text not null default '',
  hcode text not null,
  house_no text not null default '',
  moo text not null default '',
  community text not null default '',
  latitude double precision,
  longitude double precision,
  geom extensions.geometry(Point,4326),
  coordinate_source text not null default 'none' check (coordinate_source in ('jhcis','sheet','none')),
  coordinate_status text not null default 'missing',
  coordinate_distance_m double precision,
  inside_tambon boolean,
  inside_community boolean,
  volunteer_pid bigint,
  record_status text not null default '',
  review_required boolean not null default false,
  review_reason text not null default '',
  updated_at timestamptz not null default now(),
  unique(source_pcucode, hcode)
);

create table if not exists public.sync_runs (
  id bigint generated by default as identity primary key,
  source text not null,
  app_version text not null default '',
  status text not null check (status in ('running','success','failed')),
  summary jsonb not null default '{}'::jsonb,
  started_at timestamptz not null default now(),
  finished_at timestamptz
);

create table if not exists public.app_settings (
  key text primary key,
  value jsonb not null default '{}'::jsonb,
  updated_at timestamptz not null default now()
);

create index if not exists idx_profiles_community on public.profiles(community);

create index if not exists idx_profiles_volunteer_pid on public.profiles(volunteer_pid);

create index if not exists idx_volunteers_community on public.volunteers(community);

create index if not exists idx_volunteers_source_pid on public.volunteers(source_pid);

create index if not exists idx_houses_community on public.houses(community);

create index if not exists idx_houses_volunteer_pid on public.houses(volunteer_pid);

create index if not exists idx_houses_review on public.houses(review_required);

create index if not exists idx_houses_geom on public.houses using gist(geom);

create index if not exists idx_communities_geom on public.communities using gist(geom);

create index if not exists idx_tambon_geom on public.tambon_boundaries using gist(geom);

create or replace function private.set_house_geom()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if new.latitude is null or new.longitude is null then
    new.geom := null;
  elsif new.latitude between -90 and 90 and new.longitude between -180 and 180 then
    new.geom := extensions.st_setsrid(extensions.st_makepoint(new.longitude, new.latitude),4326);
  else
    raise exception 'invalid latitude/longitude';
  end if;
  new.updated_at := now();
  return new;
end;
$$;

create or replace function private.set_boundary_geom()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if new.geometry_geojson is null then
    new.geom := null;
  else
    new.geom := extensions.st_multi(
      extensions.st_setsrid(
        extensions.st_geomfromgeojson(new.geometry_geojson::text),4326
      )
    );
  end if;
  new.updated_at := now();
  return new;
end;
$$;

create or replace trigger trg_houses_geom
before insert or update of latitude, longitude on public.houses
for each row execute function private.set_house_geom();

create or replace trigger trg_communities_geom
before insert or update of geometry_geojson on public.communities
for each row execute function private.set_boundary_geom();

create or replace trigger trg_tambon_geom
before insert or update of geometry_geojson on public.tambon_boundaries
for each row execute function private.set_boundary_geom();

create or replace function private.current_role()
returns text
language sql stable security definer
set search_path = ''
as $$
  select p.role from public.profiles p
  where p.user_id = auth.uid() and p.active = true
  limit 1
$$;

create or replace function private.current_community()
returns text
language sql stable security definer
set search_path = ''
as $$
  select p.community from public.profiles p
  where p.user_id = auth.uid() and p.active = true
  limit 1
$$;

create or replace function private.current_volunteer_pid()
returns bigint
language sql stable security definer
set search_path = ''
as $$
  select p.volunteer_pid from public.profiles p
  where p.user_id = auth.uid() and p.active = true
  limit 1
$$;

revoke all on function private.current_role() from public, anon, authenticated;

revoke all on function private.current_community() from public, anon, authenticated;

revoke all on function private.current_volunteer_pid() from public, anon, authenticated;

grant execute on function private.current_role() to authenticated;

grant execute on function private.current_community() to authenticated;

grant execute on function private.current_volunteer_pid() to authenticated;

alter table public.profiles enable row level security;

alter table public.communities enable row level security;

alter table public.tambon_boundaries enable row level security;

alter table public.volunteers enable row level security;

alter table public.houses enable row level security;

alter table public.sync_runs enable row level security;

alter table public.app_settings enable row level security;

-- Profiles: users can read their own profile; admins can read/manage all profiles.
drop policy if exists profiles_select on public.profiles;

create policy profiles_select on public.profiles for select to authenticated
using (user_id = auth.uid() or private.current_role() = 'admin');

drop policy if exists profiles_admin_all on public.profiles;

create policy profiles_admin_all on public.profiles for all to authenticated
using (private.current_role() = 'admin')
with check (private.current_role() = 'admin');

-- Tambon boundary is visible to every active authenticated profile.
drop policy if exists tambon_select on public.tambon_boundaries;

create policy tambon_select on public.tambon_boundaries for select to authenticated
using (private.current_role() is not null);

-- Communities are scoped to the user's area. Admin sees all.
drop policy if exists communities_select on public.communities;

create policy communities_select on public.communities for select to authenticated
using (
  private.current_role() = 'admin'
  or name = private.current_community()
);

-- Volunteers are scoped by community; volunteer can always see own record.
drop policy if exists volunteers_select on public.volunteers;

create policy volunteers_select on public.volunteers for select to authenticated
using (
  private.current_role() = 'admin'
  or community = private.current_community()
  or source_pid = private.current_volunteer_pid()
);

-- Houses follow community scope; volunteer only sees assigned houses.
drop policy if exists houses_select on public.houses;

create policy houses_select on public.houses for select to authenticated
using (
  private.current_role() = 'admin'
  or (
    private.current_role() in ('coordinator','viewer')
    and community = private.current_community()
  )
  or (
    private.current_role() = 'volunteer'
    and volunteer_pid = private.current_volunteer_pid()
  )
);

-- Sync metadata and app settings.
drop policy if exists sync_runs_admin_select on public.sync_runs;

create policy sync_runs_admin_select on public.sync_runs for select to authenticated
using (private.current_role() = 'admin');

drop policy if exists app_settings_select on public.app_settings;

create policy app_settings_select on public.app_settings for select to authenticated
using (private.current_role() is not null);

-- No INSERT/UPDATE/DELETE policies are granted on operational tables to normal users.
-- Cloud sync uses the server-side service-role key, which must never be placed in GitHub Pages.

create or replace view public.community_report_summary
with (security_invoker = true)
as
select
  h.community,
  max(h.moo) as moo,
  count(*)::bigint as houses,
  count(*) filter (where h.volunteer_pid is not null)::bigint as assigned_houses,
  count(*) filter (where h.review_required)::bigint as review_houses,
  count(*) filter (where h.inside_tambon = false)::bigint as outside_tambon,
  count(*) filter (where h.latitude is null or h.longitude is null)::bigint as missing_coordinates,
  count(distinct h.volunteer_pid) filter (where h.volunteer_pid is not null)::bigint as volunteers_with_work
from public.houses h
group by h.community;

create or replace view public.volunteer_workload
with (security_invoker = true)
as
select
  v.source_pid,
  v.display_name,
  v.community,
  v.moo,
  v.anchor_status,
  count(h.id)::bigint as house_count,
  count(h.id) filter (where h.review_required)::bigint as review_count,
  count(h.id) filter (where h.community = v.community)::bigint as in_community_count,
  count(h.id) filter (where h.community <> v.community)::bigint as cross_community_count
from public.volunteers v
left join public.houses h on h.volunteer_pid = v.source_pid
group by v.source_pid, v.display_name, v.community, v.moo, v.anchor_status;

grant select on public.community_report_summary to authenticated;

grant select on public.volunteer_workload to authenticated;

insert into public.app_settings(key,value)
values
  ('privacy', jsonb_build_object(
    'citizen_id_13_digit_uploaded', false,
    'person_linkage', 'source_pcucode + source_pid',
    'public_access', false
  )),
  ('service_area', jsonb_build_object(
    'tambon_code', '520105',
    'tambon_name_th', 'เธเธฃเธฐเธเธฒเธ—',
    'amphoe_name_th', 'เน€เธกเธทเธญเธเธฅเธณเธเธฒเธ',
    'province_name_th', 'เธฅเธณเธเธฒเธ'
  ))
on conflict (key) do update set value = excluded.value, updated_at = now();
